# Generated by Django 4.2.20 on 2025-08-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
