# Generated by Django 4.2.20 on 2025-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe', '0003_subscription_expired_subscription_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
