# Generated by Django 4.2.20 on 2025-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe', '0004_subscription_confirmed_subscription_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='api_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
